# Build stage
FROM registry.access.redhat.com/ubi9/python-311 AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Final stage
FROM registry.access.redhat.com/ubi9/python-311
WORKDIR /app
COPY --from=builder /opt/app-root/lib/python3.11/site-packages \
                    /opt/app-root/lib/python3.11/site-packages
COPY --from=builder /opt/app-root/bin/gunicorn \
                    /opt/app-root/bin/gunicorn
COPY app.py .
EXPOSE 5000
ENV PYTHONPATH=/app
CMD ["/opt/app-root/bin/gunicorn", "--bind", "0.0.0.0:5000", \
     "--workers", "2", "--timeout", "60", "app:app"]
